import { join } from "node:path";
import type { Page } from "@playwright/test";

/**
 * Returns the storageState file path that Tier-2 tests should reuse when
 * authenticated as the seeded primary user. Generated by global-setup.
 */
export function primaryAuthStatePath(): string {
  return join(process.cwd(), "tests/e2e/.auth/primary.json");
}

/**
 * Tier-2 gate. Each Supabase-backed test should call
 *   if (!supabaseE2EEnabled()) test.skip(true, "...");
 * so the suite still passes on machines without Docker / Supabase.
 */
export function supabaseE2EEnabled(): boolean {
  return process.env.BELLA_E2E_SUPABASE === "1";
}

/**
 * Pre-stamps the onboarding-ack flag in localStorage. Use before the first
 * navigation so the gate doesn't redirect Tier-2 tests to /onboarding.
 *
 * The onboarding gate (`src/components/shell/onboarding-gate.tsx`) reads
 * `bella:onboarding-ack-v1` and treats `"true"` as acknowledged.
 */
export async function stampOnboardingAck(page: Page): Promise<void> {
  await page.addInitScript(() => {
    try {
      window.localStorage.setItem("bella:onboarding-ack-v1", "true");
    } catch {
      // private mode or quota — tests can still proceed; the gate will just
      // bounce them to /onboarding and they'll be marked skipped where used.
    }
  });
}
